### ISSUE TITLE
Unable to run a peer 

### ISSUE THREAD

**Issue by anu1097** [P2PSP/I-want-to-use-it#1]
While trying to use the library to run a peer using this one command mentioned in Readme 
./peer --splitter_addr 150.214.150.68 --splitter_port 4552 > /dev/null &
vlc http://localhost:9999 &

I tried mpv http://localhost:9999 &

I kept getting these errors -

Playing: http://localhost:9999
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(error(111, 'Connection refused'),))
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
[ffmpeg] tcp: Connection to tcp://localhost:9999 failed: Connection refused
Failed to open http://localhost:9999.

Exiting... (Errors when loading file)

**Comment by cristobalmedinalopez** [comment]
In order to ensure that 9999 port is not being used by other process. Could you try again running the peer in this way?

./peer --splitter_addr 150.214.150.68 --splitter_port 4552 --player_port 7788 > /dev/null &
vlc http://localhost:7788 &

**Comment by anu1097** [comment]
I got the same output as before which were the same for the as exact commands suggested by you-

**anuraag@anu123:~/p2psp-console/bin$** ./peer --splitter_addr https://www.youtube.com/watch?v=jTi7VtrLL0k --splitter_port 4552 --player_port 7788 > /dev/null &
[10] 3244
[9]   Exit 1                  ./peer --splitter_addr 150.214.150.68 --splitter_port 4552 --player_port 77888 > /dev/null
**anuraag@anu123:~/p2psp-console/bin$** mpv http://localhost:7788 
&[11] 3246
**anuraag@anu123:~/p2psp-console/bin$** Playing: http://localhost:7788
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(error(111, 'Connection refused'),))
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
[ffmpeg] tcp: Connection to tcp://localhost:7788 failed: Connection refused
Failed to open http://localhost:7788.


Exiting... (Errors when loading file)

[10]   Exit 255                ./peer --splitter_addr https://www.youtube.com/watch?v=jTi7VtrLL0k --splitter_port 4552 --player_port 7788 > /dev/null
[11]   Exit 2                  mpv http://localhost:7788

**Comment by cristobalmedinalopez** [comment]
Let me check if the splitter at 150.214.150.68 is running. In the meantime you could run a local team instead (see local team section https://github.com/P2PSP/I-want-to-use-it).
